- elements/nuxeo-app.html
- elements/nuxeo-web-ui-bundle.html
- elements/routing.html
This moves `<nuxeo-browser>` and `<nuxeo-search-results>` back to the app.
Also refactors the search on load accordingly (simplifying things along the way).
> NXP-22427: keep main pages by default

- elements/nuxeo-admin/nuxeo-workflow-analytics.html
Use dedicated API endpoint workflowModel to get list of available workflows, instead of hard-coding to two bundles workflows.
> Fetch workflows from repository instead of hard-coding

- elements/document/nuxeo-document-edit.html
- elements/elements.html
- elements/nuxeo-document-actions/nuxeo-document-edit-button.html
- elements/nuxeo-web-ui-bundle.html
restores the previous version of `nuxeo-document-edit`, just adding the div class="scrollable" .
renames `nuxeo-document-edit-action` to `nuxeo-document-edit-button`
> NXP-22989: moves dialog to nuxeo-document-edit-button

- i18n/messages-de.json
- i18n/messages-es-ES.json
- i18n/messages-eu.json
- i18n/messages-fr.json
- i18n/messages-ja.json
- i18n/messages-pt-PT.json
- i18n/messages-sv-SE.json
Despite the i18n/messages-eu.json being totally in english, the key was backported in the correct language.
> NXP-25082: Add missing translated documentAttachments.empty key

- .gitignore
- gulpfile.js
- index.html
- manifest.json
- package.json
- polymer.json
- src/main/resources/OSGI-INF/browser-cache-contrib.xml
- src/main/resources/web/nuxeo.war/ui/index.jsp
- sw.js
SW on dev mode only so no need for reload timestamp as hotreload is dev mode only.
SW matching js and html files for agressive caching of these. Other resources are not dynamically loaded so they rely on default static cache (which is disable for js and html files).
SW does network first so it hits browser cache (no stale responses unless offline).
> NXP-25700: add cache service worker

- elements/nuxeo-suggester/nuxeo-suggester.html
- themes/base.html
Not really sure about the aim of this task, so I add 2 new variables in the default theme for the `paper-input` element, and I fixed a display bug on mobile when the result title is long. For that second point, you can find more informations here: https://css-tricks.com/flexbox-truncated-text/
> NXP-25344: Use CSS variables and fix nuxeo-suggester display on mobile

- i18n/messages.json
Related to: https://github.com/nuxeo/nuxeo-easyshare/pull/36
> NXP-25524: add missing label for easyshare dialog

- elements/nuxeo-web-ui-bundle.html
The `nuxeo-collection-results` element does not exist since 0.10
> NXP-26854: remove obsolete contribution.

- elements/diff/nuxeo-diff.js
The specifications of this task was not really clear, so I assumed that the diff page should always display the current version on the right screen, and the previous one on the left screen. So if the current version is not the last one, the versions following the current one will not be displayed.
> NXP-25939: Reverse starting order on document diff

- addons/nuxeo-csv/elements/nuxeo-document-import-csv.js
- elements/nuxeo-app.js
- elements/nuxeo-document-create-popup/nuxeo-document-create-popup.js
- elements/nuxeo-document-creation/nuxeo-document-creation-behavior.js
this fix is related to https://jira.nuxeo.com/browse/NXP-26429, and mainly on https://jira.nuxeo.com/browse/NXP-26429?focusedCommentId=386657&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-386657
_Error message on the path suggester should not appear if user has write permission_ : to solve this issue i duplicate some code in `nuxeo-document-import-csv.js` from `nuxeo-document-create-popup.js` to be able to update the parent property and the whole validation is ensured by the behaviour `nuxeo-document-creation-behavior.js`.
But unfortunately we end up with a duplicated code, to solve the problem caused by the two way binding when we add an extension to exiting slot.
with @guirenard we worked on a 2nd solution …
> NXP-26429: Improve error handling / permissions on CSV import

- elements/document/nuxeo-document-create.js
This branch has 3 commits but it is the second one that I want to discuss with you.
In [NXP-27037](https://jira.nuxeo.com/browse/NXP-27037) we are asked to maintain two lines with ellipsis. I'm proposing `-webkit-line-clamp` to solve this question. The only place where it isn't supported now is Firefox 67, but it is already working on Firefox Nightly [(check it out here)](https://caniuse.com/#search=webkit-line-clamp). 
Today, the expected behaviour on Firefox 67 is simply the omission of the rest of the text. Do you think this could be a good solution?
> NXP-27037: ellipses and tooltip on document type create form

- Dockerfile.dev
- skaffold.yaml
Goal of this image is to allow usage when developing. ie for a custom addon:
```
version: "3"
services:
webui:
image: nuxeo-web-ui/dev
environment:
- NUXEO_PACKAGES=nuxeo-dam mine
volumes:
- .:/ui/addons/mine:ro
nuxeo:
image: nuxeo/nuxeo:10.10
environment:
- NUXEO_PACKAGES=nuxeo-dam
```
Here's a sample use case for usage as a builder image https://github.com/nelsonsilva/nuxeo-nightly
> NXP-27264: add nuxeo-web-ui/dev builder image

- elements/nuxeo-document-tree/nuxeo-document-tree.js
Part of the fix was reverting some code done under https://github.com/nuxeo/nuxeo-web-ui/commit/b1071ccca1e1e7ebe9f10eb1649adb406002fc04#diff-ae7d24c90db150181fbbdac8f78a22de
> NXP-26749: ensure that only folderish docs are shown

- elements/nuxeo-document-history/nuxeo-document-history.js
The second commit is, in fact, a workaround for some limitations that we have on our event system.
Ideally, we would have information provided by the server to know which is the type of event's comment. Then we could have a formatter approach as we have for Diff.
> NXP-28785: compare audit comment using regex

- addons/nuxeo-drive/elements/nuxeo-drive-sync-roots-management.js
- i18n/messages.json
The `driveSyncRootsManagement.root.disable` label was lost at some point.
Reintroducing it to solve the tooltip display on the delete button of a synchronized root.
It is used here: https://github.com/nuxeo/nuxeo-web-ui/blob/c7e67299e9c35803d8c25104324ba37e54787f4d/addons/nuxeo-drive/elements/nuxeo-drive-sync-roots-management.js#L103-L107
Signed-off-by: Mickaël Schoentgen <mschoentgen@nuxeo.com>
> NXP-28787: add missing translation label for Nuxeo Drive

- i18n/messages.json
The `driveSyncRootsManagement.root.disable` label was lost at some point.
Reintroducing it to solve the tooltip display on the delete button of a synchronized root.
The JS code cleanup (+fix) is here: https://github.com/nuxeo/nuxeo/pull/3945
> [10.10] NXP-28787: add missing translation label for Nuxeo Drive

- elements/nuxeo-admin/nuxeo-workflow-analytics.js
Note: the `_labels` method is only used for this chart in particular, so we won't be translating labels elsewhere.
Will post a pipeline status ASAP.
> NXP-28338: show translated taskName instead of action in workflow analytics

- elements/nuxeo-admin/nuxeo-workflow-analytics.html
> NXP-28338: show translated taskName instead of action in workflow analytics (10.10)

- package.json
This issue is visible for the following `jsplumb` versions:
- `2.13.3` (latest)
- `2.13.2`
- `2.13.1`
On `2.13.0` (released 3 months ago) the connectors are properly drawn.
> NXP-29221: lock jsplumb version to 2.13.0

- addons/nuxeo-drive/elements/nuxeo-drive-edit-button.js
- addons/nuxeo-drive/elements/nuxeo-drive-sync-toggle-button.js
Applies the same code change to the sync root icon to conform with other icons.
Before:
After:
> NXP-29241: fix the Direct Edit icon tooltip position

- Jenkinsfiles/web-ui-pipeline.groovy
- plugin/web-ui/addon/build.xml
This is a temporary measure to allow nightly build to go through. We would undo this as soon as we have continuous releases on Web UI and could move the nightly build to JX.
> NXP-29305: force packages as npm registry

- elements/workflow/nuxeo-document-task-assignment-popup.js
Changed value="[[comment]]" to value="{{comment}}" in nuxeo-textarea arguments, as this is an output rather than an input in this "screen".
Tested manually and successfully the change in LTS 2019
> NXP-29347: nuxeo-document-task-assignment-popup outputs comment

- elements/nuxeo-app.js
The goal is to navigate to the document referenced by the action response. Additionally, we no longer rely on the `document-updated` event to close the dialog, so we now have two new (and more specific) events: `save` and `cancel`.
> NXP-29210: rely on the current document id if available

- elements/routing.js
We need the `/.../s` flag for `.` to match with `\n` characters.
> NXP-28889: fix navigation when document url contains newline characters

- elements/routing.html
> NXP-28889: fix navigation when document url contains newline characters (10.10)

- .npmrc
- Jenkinsfile
- README.md
Depends on https://github.com/nuxeo/jx-webui-env/pull/21.
> WEBUI-30: use npm-public as the default repo for nuxeo scoped packages

- elements/nuxeo-clipboard/nuxeo-clipboard.js
Ok, I'm opening the PR for further discussion on the topic.
- `nuxeo-clipboard` is using the `nuxeo-document-storage` to store the documents in the clipboard. 
- `nuxeo-document-storage` is [updating](https://github.com/nuxeo/nuxeo-web-ui/blob/master/elements/nuxeo-document-storage/nuxeo-document-storage.js#L85) the `documents` array and [notifying](https://github.com/nuxeo/nuxeo-web-ui/blob/master/elements/nuxeo-document-storage/nuxeo-document-storage.js#L95) the `nuxeo-clipboard`
- However, `nuxeo-clipboard` is not listening to array splices or any update inside the `documents` property (`!canPaste(documents, targetDocument)` is only triggered when the `documents` changes).
What do you think would be a good approach to handle this? 
I thought about listening to splices …
> WEBUI-41: refresh clipboard based on content update

- themes/base.js
Still to be discussed. The best solution should be to define the `--nuxeo-button-icon-margin-end` [instead ](https://github.com/nuxeo/nuxeo-web-ui/blob/0cab8027de899ec0bc1344136d40801daa5fed5f/themes/base.js#L560)
> WEBUI-28: fix icon misalignment in create dialog

- elements/nuxeo-results/nuxeo-results.js
Don't see an easy option for this one. The problem is caused by two elements ([nuxeo-search-form](https://github.com/nuxeo/nuxeo-web-ui/blob/master/elements/search/nuxeo-search-form.js#L922) and [nuxeo-results](https://github.com/nuxeo/nuxeo-web-ui/blob/master/elements/nuxeo-results/nuxeo-results.js#L454)) performing a `fetch` in the page provider which debounces requests. 
The debounce itself is not bad, but if the request made by the `nuxeo-search-form` is canceled because the `nuxeo-results` performs another request due to a `view change`, then we get this issue. The `nuxeo-search-form` expects the request to resolve to [remove the loading state](https://github.com/nuxeo/nuxeo-web-ui/blob/master/elements/search/nuxeo-search-form.js#L925).
Feedback is very welcome 😄
> WEBUI-44: enqueue debounce to prevent request cancelling.

- elements/search/nuxeo-search-form.js
Based on the [existing logic for `<nuxeo-document-create>`](https://github.com/nuxeo/nuxeo-web-ui/blob/e83d9d314edfc65e13470c6295df84a7885770b3/elements/document/nuxeo-document-create.js#L348-L360).
> WEBUI-64: prevent triggering search when form is invalid

- elements/nuxeo-document-comments/nuxeo-document-comment.html
Backporting a fix already on master done under comment's migration to elements.
Pipeline ran multiple times with random/different errors each time 🤦🏼‍♂️
> WEBUI-102: validate comment's text type (10.10)

- package.json
> WEBUI-137: update gulp-imagemin to fix minification of pdfjs viewer from elements (10.10)

- elements/directory/l10nxvocabulary/nuxeo-l10nxvocabulary-edit-layout.html
Backport of https://github.com/nuxeo/nuxeo-web-ui/pull/1155
> WEBUI-232: set vocabulary parent to root when none is provided

- elements/nuxeo-collections/nuxeo-collection-remove-action.js
JSF UI is relying in the platform CollectionManager to assert if the user [can add/remove](https://github.com/nuxeo/nuxeo/blob/master/modules/platform/nuxeo-collections/src/main/java/org/nuxeo/ecm/collections/core/CollectionManagerImpl.java#L132) items from a collection. This checks if the user has the WriteProperties permission on the collection, and on Web UI we are only do the assertion for the [ReadCanCollect](https://github.com/nuxeo/nuxeo/blob/8ce732309dc35ebe6c53aa8e0dd52757e8faf74a/modules/platform/nuxeo-collections/src/main/resources/OSGI-INF/collection-security-contrib.xml#L9) permission (that includes both the Read and WriteProperties permissions). 
To make this consistent, we should check for the `WriteProperties` permission too.
> WEBUI-132: enable remove from collection button when user has WriteProperties

- addons/easyshare/elements/nuxeo-easyshare-share-link.js
- addons/nuxeo-platform-3d/elements/nuxeo-3d-preview.js
- addons/nuxeo-template-rendering/elements/nuxeo-render-template-button.js
- elements/diff/nuxeo-versions-diff-button.js
- elements/directory/nuxeo-vocabulary-management.js
- elements/document/nuxeo-document-create.js
- elements/document/nuxeo-document-form-layout.js
- elements/document/nuxeo-document-import.js
- elements/nuxeo-cloud-services/nuxeo-cloud-consumers.js
- elements/nuxeo-cloud-services/nuxeo-cloud-providers.js
- elements/nuxeo-cloud-services/nuxeo-tokens-behavior.js
- elements/nuxeo-csv-export/nuxeo-csv-export-button.js
- elements/nuxeo-document-attachments/nuxeo-document-attachments.js
- elements/nuxeo-document-bulk-actions/nuxeo-download-documents-button.js
- elements/nuxeo-document-create-popup/nuxeo-document-create-popup.js
- elements/nuxeo-document-viewer/nuxeo-document-viewer.js
- elements/nuxeo-dropzone/nuxeo-dropzone.js
- elements/nuxeo-note-editor/nuxeo-note-editor.js
- elements/nuxeo-publication/nuxeo-document-publications.js
- elements/nuxeo-publication/nuxeo-internal-publish.js
- elements/nuxeo-publication/nuxeo-unpublish-button.js
- elements/nuxeo-results/nuxeo-document-content-behavior.js
- elements/nuxeo-results/nuxeo-document-trash-content.js
- elements/nuxeo-user-authorized-apps.html
- elements/nuxeo-workflow-graph/nuxeo-workflow-graph.js
- elements/search/nuxeo-search-form.js
- elements/workflow/nuxeo-document-task.js
- index.js
Depends on https://github.com/nuxeo/nuxeo-elements/pull/418.
As a POC, I modified `nuxeo-csv-export-button`, which is quite easy to test on the UI:
1. Navigate to a folder with several leaf documents
2. Switch network trotting to Fast or even Slot 3G.
3. Click the export button (you should still see the toast "CSV export is running")
4. Navigate to a leaf document
5. You will see the toast "CSV export is ready" (which would not show up before, because it is being fired from an element that is no longer stamped)
> WEBUI-345: make nuxeo-app the fallback notification target

- elements/nuxeo-app.js
- elements/nuxeo-document-creation/nuxeo-document-creation-behavior.js
- elements/nuxeo-document-versions/nuxeo-document-versions.js
- elements/nuxeo-dropzone/nuxeo-dropzone.js
- elements/nuxeo-publication/nuxeo-publication-info-bar.js
- elements/nuxeo-restore-version-button/nuxeo-restore-version-button.js
- ftest/features/versions.feature
- index.js
- legacy.js
- packages/nuxeo-web-ui-ftest/features/step_definitions/browser.js
- packages/nuxeo-web-ui-ftest/features/step_definitions/document.js
- packages/nuxeo-web-ui-ftest/features/step_definitions/login.js
- packages/nuxeo-web-ui-ftest/features/step_definitions/search.js
- packages/nuxeo-web-ui-ftest/features/step_definitions/support/ui_config.js
- packages/nuxeo-web-ui-ftest/pages/helpers.js
- packages/nuxeo-web-ui-ftest/pages/ui.js
- packages/nuxeo-web-ui-ftest/pages/ui/administration.js
- packages/nuxeo-web-ui-ftest/pages/ui/browser.js
- packages/nuxeo-web-ui-ftest/pages/ui/browser/collapsible_document_page.js
Depends on https://github.com/nuxeo/nuxeo-elements/pull/407.
- Adds `@config(key, value)` cucumber tag to enable a given configuration property for a specific scenario or feature file.
- Adds a hook to the application where it waits for an event `automation-ready` to be fired before defining the `nuxeo-app` element, IF automation is enabled (i.e, the browser was launched by webdriver).
- Adds new helper methods `url` and `refresh`, which encapsulate the respective webdriver commands but also sends in the properties defined in the tests using the `@cofig` tag and then fire the `automation-ready` event. This means that the application will only load after the configuration has been loaded.
Note that the diff for nuxeo-app looks huge, but I just wrapped the nuxeo-app element definition with: …
> WEBUI-333: set ui config from functional tests

- elements/nuxeo-admin/nuxeo-distribution-analytics.html
- i18n/messages-ar.json
- i18n/messages-de.json
- i18n/messages-es-ES.json
- i18n/messages-eu.json
- i18n/messages-fr.json
- i18n/messages-he.json
- i18n/messages-id.json
- i18n/messages-it.json
- i18n/messages-ja.json
- i18n/messages-nl.json
- i18n/messages-pt-PT.json
- i18n/messages-sv-SE.json
- i18n/messages-zh-CN.json
- i18n/messages.json
- index.html
- src/main/resources/OSGI-INF/web-ui-properties.xml
Backport of the https://github.com/nuxeo/nuxeo-web-ui/pull/1192.
Does not include the backport of WEBUI-285 and WEBUI-286.
> WEBUI-136: conditionally disable nuxeo-distribution-analytics with user defined threshold -10.10
