elements/nuxeo-browser/nuxeo-browser.html

NXP-20814: Fix typo

---

elements/nuxeo-document-tree/nuxeo-document-tree.html

NXP-21471: Forces update of rootDocument when name of currentDocument changes

---

build.xml

PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-grenard-maven3/139/

fix-NXP-22645-bowerSymLink-9.2

---

elements/document/nuxeo-document-import.html

Add IDs to paper-buttons for testing purposes

NXP-23131: Add IDs to paper-buttons on nuxeo-document-import

---

src/main/resources/OSGI-INF/login-startup-page-web-contrib.xml
src/main/resources/OSGI-INF/url-codecs-web-contrib.xml

PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-ataillefer/64/

task-NXP-23293-make-web-ui-default

---

elements/nuxeo-document-creation/nuxeo-document-creation-behavior.html

for nbme documents with complex fields within complex fields. the creation form was producing an error when we try to create it. We are working off the PRJ725-webui branch in NBME repo, using 1.02 snapshot for web ui. We are using master branch for studio project. From any collection that can add media, selecting media to load the creation form produces an error.

NXP-23141: Initialize complex fields within complex fields in doc creation in web ui errors 

---

elements/document/collection/nuxeo-collection-view-layout.html
elements/document/favorites/nuxeo-favorites-view-layout.html
elements/nuxeo-app.html
elements/nuxeo-collections/nuxeo-collections.html
elements/nuxeo-collections/nuxeo-favorites.html
elements/search/nuxeo-search-form.html
test/index.html
test/nuxeo-collections/nuxeo-collections-responses.js
test/nuxeo-collections/nuxeo-collections.html
test/nuxeo-collections/nuxeo-favorites-responses.js
test/nuxeo-collections/nuxeo-favorites.html

PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-grenard-maven3/182/

fix-NXP-23331-collectionLazyScrolling

---

elements/nuxeo-document-bulk-actions/nuxeo-download-documents-button.html
elements/nuxeo-web-ui-bundle.html

PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-grenard-maven3/190/

feature-NXP-23481-recurseBulkDown

---

elements/nuxeo-document-info-bar/nuxeo-document-info-bar.html

The closing `dom-module` was in the wrong place.

Fix element structure

---

elements/document/collection/nuxeo-collection-view-layout.html
elements/nuxeo-collections/nuxeo-collections.html
elements/nuxeo-collections/nuxeo-favorites.html
elements/nuxeo-results/nuxeo-default-results.html

PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-grenard-maven3/197/

fix-NXP-23208-noDomainUserWorkspace

---

themes/dark/theme.html
themes/default/theme.html

Remove invalid CSS color values.

NXP-23082-fix-color

---

elements/elements.html
elements/nuxeo-results/nuxeo-document-content.html
elements/nuxeo-results/nuxeo-results.html
elements/nuxeo-web-ui-bundle.html

PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-grenard-maven3/206/

feature-NXP-23314-orderedFolder

---

elements/nuxeo-web-ui-bundle.html
elements/search/nxql/nuxeo-nxql-search-form.html

PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume/356/

cleanup-NXP-24486-ischeckedinversion

---

elements/nuxeo-document-creation/nuxeo-document-creation-behavior.html

Handle Directory field default value in creation form

NXP-24681 Handle Directory field default value in creation form

---

elements/nuxeo-app.html

PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-grenard-maven3/217/

fix-NXP-24818-fetchVocaParent

---

elements/nuxeo-document-bulk-actions/nuxeo-delete-documents-button.html
elements/nuxeo-document-bulk-actions/nuxeo-untrash-documents-button.html
elements/nuxeo-document-info-bar/nuxeo-document-info-bar.html
elements/nuxeo-results/nuxeo-document-trash-content.html

feature-NXP-webUITrash-9.10

---

elements/nuxeo-dropzone/nuxeo-dropzone.html

PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-ncunha/2/

fix-NXP-25005-PrefixedRepeatedContributors

---

elements/nuxeo-results/nuxeo-results.html

fix-NXP-24514-complexOrdering

---

elements/nuxeo-results/nuxeo-results.html

fix-NXP-24514-complexOrdering-9.10

---

elements/search/nuxeo-search-form.html

Debounce doc selection to reduce requests.

NXP-24894: debounce document selection on search form queue

---

i18n/i18n.html
src/main/resources/META-INF/MANIFEST.MF
src/main/resources/OSGI-INF/browser-cache-contrib.xml
src/main/resources/web/nuxeo.war/ui/index.jsp

fix-NXP-25139-webui-cache

---

elements/nuxeo-document-bulk-actions/nuxeo-delete-documents-button.html
elements/nuxeo-web-ui-bundle.html

fix-NXP-25160-noBulkPermanentDelete

---

elements/nuxeo-document-bulk-actions/nuxeo-delete-documents-button.html

fix-NXP-25160-noBulkPermanentDelete-9.10

---

elements/nuxeo-app.html
elements/routing.html
index.css
index.html
polymer.json
src/main/resources/web/nuxeo.war/ui/index.jsp

Note that the `[unresolved]` selector precedes all css rules to prevent bleed on shady css.

NXP-25202: style unresolved nuxeo-app

---

elements/nuxeo-clipboard/nuxeo-clipboard.html
elements/nuxeo-document-storage/nuxeo-document-storage.html

PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-ncunha/3/

fix-NXP-25103-TitleNotUpdatedInClipboard

---

elements/routing.html

PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-ajusto/4/

fix-NXP-25310-group-name-slash

---

elements/routing.html

PR created from https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-ajusto-9.10/4/

fix-NXP-25310-group-name-slash-9.10

---

elements/routing.html
index.html
polymer.json
src/main/resources/web/nuxeo.war/ui/index.jsp

fix-NXP-25323-pagejs

---

elements/nuxeo-app.html
elements/nuxeo-app/nuxeo-expired-session.html
i18n/messages.json

Depends on nuxeo/nuxeo-elements#27.

NXP-25021: display a login banner when the session is expired

---

elements/nuxeo-app.html
elements/nuxeo-app/nuxeo-expired-session.html
i18n/messages.json

Depends on nuxeo/nuxeo-elements#30.

NXP-25021: display a login banner when the session is expired (9.10)

---

src/main/resources/OSGI-INF/browser-cache-contrib.xml

PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-grenard-maven3/225/

imp-NXP-25385-If-None-Match

---

elements/nuxeo-app.html
elements/nuxeo-data-grid/nuxeo-document-grid-thumbnail.html

fix-NXP-25302-gridPerf

---

bower.json

This reverts commit 8a9a67f23e27bfd6ab80b54c55aaf5de651eff7a.

NXP-25606: revert lock dependency on vaadin-button

---

elements/nuxeo-note-editor/nuxeo-note-editor.html
i18n/messages.json

With backport for [NXP-24547](https://jira.nuxeo.com/browse/NXP-24547).

NXP-25282: add button to toggle between source and WYSIWYG for html editing

---

src/main/resources/OSGI-INF/web-ui-properties.xml

feature-NXP-25512-defaultDateFormat

---

elements/search/default/nuxeo-default-search-results.html
elements/search/expired/nuxeo-expired-search-results.html
elements/search/trash/nuxeo-trash-search-results.html

fix-NXP-25320-aggNav

---

elements/nuxeo-results/nuxeo-document-content.html
elements/nuxeo-results/nuxeo-document-trash-content.html
elements/nuxeo-web-ui-bundle.html

PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-grenard-maven3/257/

fix-NXP-25762-browseTras

---

elements/diff/nuxeo-document-diff-button.html
elements/diff/nuxeo-versions-diff-button.html
elements/elements.html
elements/nuxeo-browser.html
elements/nuxeo-collections/nuxeo-collection-move-bottom-action.html
elements/nuxeo-collections/nuxeo-collection-move-down-action.html
elements/nuxeo-collections/nuxeo-collection-move-top-action.html
elements/nuxeo-collections/nuxeo-collection-move-up-action.html
elements/nuxeo-collections/nuxeo-collection-remove-action.html
elements/nuxeo-document-actions/nuxeo-clipboard-toggle-button.html
elements/nuxeo-document-actions/nuxeo-document-edit-button.html
elements/nuxeo-document-blob/nuxeo-document-blob.html
elements/nuxeo-document-bulk-actions/nuxeo-add-to-collection-documents-button.html
elements/nuxeo-document-bulk-actions/nuxeo-clipboard-documents-button.html
elements/nuxeo-document-bulk-actions/nuxeo-delete-documents-button.html
elements/nuxeo-document-bulk-actions/nuxeo-download-documents-button.html
elements/nuxeo-document-bulk-actions/nuxeo-untrash-documents-button.html
elements/nuxeo-results/nuxeo-results.html
themes/base.html

Depends on nuxeo/nuxeo-ui-elements#276.

NXP-25146: add responsive action menus to web ui

---

elements/document/nuxeo-document-edit.html
elements/document/nuxeo-document-form-layout.html
elements/elements.html
elements/nuxeo-document-actions/nuxeo-document-edit-button.html
elements/nuxeo-document-actions/nuxeo-document-form-button.html

fix-NXP-26010-document-form-layout

---

elements/elements.html
elements/nuxeo-app.html
elements/nuxeo-web-ui-bundle.html
src/main/resources/OSGI-INF/web-ui-properties.xml

Depends on https://github.com/nuxeo/nuxeo/pull/2481, https://github.com/nuxeo/nuxeo/pull/2474, https://github.com/nuxeo/nuxeo-elements/pull/37 and https://github.com/nuxeo/nuxeo-ui-elements/pull/291

NXP-26002: blob enrichers + appLinks enricher

---

elements/nuxeo-results/nuxeo-document-content.html
elements/nuxeo-results/nuxeo-document-trash-content.html
elements/nuxeo-results/nuxeo-results.html

Depends on nuxeo/nuxeo-ui-elements#295.

NXP-25637: prevent fetch error when loading a view on nuxeo-results

---

elements/document/nuxeo-collapsible-document-page.html
elements/document/nuxeo-document-page.html
elements/nuxeo-app/nuxeo-page.html
elements/nuxeo-results/nuxeo-document-content.html
elements/nuxeo-results/nuxeo-document-trash-content.html
elements/nuxeo-results/nuxeo-results.html
elements/nuxeo-web-ui-bundle.html
i18n/messages.json
themes/base.html

Depends on nuxeo/nuxeo-ui-elements#299.

 NXP-25636: move document details to collapsible sidebar

---

elements/nuxeo-document-comments/nuxeo-document-comment-thread.html
elements/nuxeo-document-comments/nuxeo-document-comment.html

Related to: https://github.com/nuxeo/plugin-nuxeo-web-ui/pull/83

NXP-25839: add "id" or "name" attributes for functional testing

---

elements/nuxeo-csv-export/nuxeo-csv-export-button.html

Depends on https://github.com/nuxeo/nuxeo/pull/2531 and https://github.com/nuxeo/nuxeo-elements/pull/40

NXP-26171: use Bulk.RunAction for csv export

---

elements/document/nuxeo-document-form-layout.html

Not sure at all with this code, but it seems to work. I make a lot of shadowRoot querySelector and it's seems not very generic and reliable. Any suggestion would be welcome!

NXP-25935: Focus first field with error, and scroll to it

---

elements/workflow/nuxeo-document-task.html

PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-grenard-maven3/268/

fix-NXP-20450-validateTaks

---

elements/document/nuxeo-document-page.html

Related to: https://github.com/nuxeo/nuxeo-ui-elements/pull/306

NXP-26317: add overflow hidden for main page

---

elements/nuxeo-publication/nuxeo-internal-publish.html
elements/nuxeo-publication/nuxeo-publication-info-bar.html
elements/nuxeo-web-ui-bundle.html
i18n/messages.json

fix-NXP-26477-pubBugs

---

elements/nuxeo-admin.html
elements/nuxeo-admin/nuxeo-user-group-management-page.html
elements/nuxeo-app.html
elements/nuxeo-web-ui-bundle.html
elements/routing.html

task-NXP-25574-page-sub-routing

---

elements/nuxeo-app.html
gulpfile.js
index.html
polymer.json
src/main/resources/web/nuxeo.war/ui/index.jsp

fix-NXP-26277-dynPageLoading

---

elements/nuxeo-document-info-bar/nuxeo-document-info-bar.html

https://qa2.nuxeo.org/jenkins/job/WebUI/job/web-ui-pipeline-9.10/148/

NXP-25581: move workflow-graph element to avoid FT errors (9.10)

---

elements/elements.html
elements/nuxeo-app.html
elements/nuxeo-results/nuxeo-document-content-behavior.html
elements/nuxeo-results/nuxeo-document-content.html
elements/nuxeo-results/nuxeo-document-trash-content.html
elements/nuxeo-results/nuxeo-results.html

feature-NXP-26184-document-content-customizable

---

elements/nuxeo-results/nuxeo-results.html

Depends on nuxeo/nuxeo-ui-elements#338.

NXP-26513: remove items and filters update optimizations on nuxeo-results

---

elements/search/nuxeo-search-form.html

Pipeline: https://qa.nuxeo.org/jenkins/view/TestAndPush/job/web-ui-pipeline-ncunha/102/

NXP-26655: ensure no objects are sent as query parameters on search forms (Backport 10.10)

---

elements/workflow/nuxeo-document-task.html

fix-NXP-26629-taskValidation-10

---

elements/workflow/nuxeo-document-task.html

fix-NXP-26629-taskValidation

---

elements/workflow/nuxeo-document-task.html

fix-NXP-26629-taskValidation-9.10

---

elements/nuxeo-document-viewer/nuxeo-document-viewer.html

Cannot cherry-pick the commit because would backport unwanted changes to the element.

NXP-26819: preventing unnecessary rendering when no data is available.

---

elements/directory/nuxeo-vocabulary-management.html

https://qa.nuxeo.org/jenkins/job/web-ui-pipeline-ncunha/118/

NXP-26556: sort vocabulary entries

---

elements/directory/nuxeo-vocabulary-management.html

https://qa.nuxeo.org/jenkins/job/web-ui-pipeline-ncunha/119/

NXP-26556: sort vocabulary entries (Backport 10.10)

---

elements/directory/nuxeo-vocabulary-management.html

https://qa2.nuxeo.org/jenkins/job/WebUI/job/web-ui-pipeline-9.10/162/

NXP-26556: sort vocabulary entries (Backport 9.10)

---

elements/nuxeo-app.html
index.html

fix-NXP-26816-taskFetch

---

elements/nuxeo-app.html
index.html

fix-NXP-26816-taskFetch-10.10

---

elements/nuxeo-results/nuxeo-results.html

fix-NXP-26176-spreadsheet-columns-910

---

gulpfile.js

fix-ELEMENTS-835-alloyI18N-10.10

---

gulpfile.js

fix-ELEMENTS-835-alloyI18N-9.10

---

elements/nuxeo-collections/nuxeo-favorites.html

fix-ELEMENTS-889-favorites-thumbnails

---

elements/nuxeo-collections/nuxeo-favorites.html

Manual PR since pipeline build appears to be broken.

NXP-26905: fix thumbnails display in favorites

---

gulpfile.js

fix-NXP-26916-babel-helpers

---

addons/amazon-s3-online-storage/index.js
elements/nuxeo-dropzone/nuxeo-dropzone.js
i18n/messages.json

imp-NXP-26620-abortUpload

---

elements/nuxeo-app.js

fix-NXP-27167-missingBehaviorImport

---

Jenkinsfiles/web-ui-pipeline.groovy

fix-NXP-27223-pipeline

---

elements/document/nuxeo-document-layout.js

Pipeline: https://qa.nuxeo.org/jenkins/view/TestAndPush/job/web-ui-pipeline-ncunha/132/
Related Elements' PR: https://github.com/nuxeo/nuxeo-elements/pull/78

NXP-27334: change document layout validation's order

---

elements/document/nuxeo-document-layout.html

Related UI Elements' PR: https://github.com/nuxeo/nuxeo-ui-elements/pull/390

NXP-27334: change document layout validation's order (Backport 10.10)

---

index.html
src/main/resources/OSGI-INF/web-ui-properties.xml

Related UI-Elements PR: https://github.com/nuxeo/nuxeo-ui-elements/pull/391

NXP-27343: add firstDayOfWeek as a global configuration (Backport 10.10)

---

elements/search/nuxeo-search-form.js

Elements' ticket: https://github.com/nuxeo/nuxeo-elements/pull/92
Pipeline: https://qa.nuxeo.org/jenkins/view/TestAndPush/job/web-ui-pipeline-ncunha/165/

NXP-27063: remove param filtering logic from search form

---

elements/search/nuxeo-search-form.html

Elements' ticket: https://github.com/nuxeo/nuxeo-elements/pull/93
Pipeline: https://qa2.nuxeo.org/jenkins/job/WebUI/job/web-ui-pipeline-10.10/74/

NXP-27063: remove param filtering logic from search form (Backport 10.10)

---

elements/nuxeo-results/nuxeo-document-trash-content.js
elements/nuxeo-results/nuxeo-results.js
elements/nuxeo-web-ui-bundle.html
ftest/test/features/trash.feature
packages/nuxeo-web-ui-ftest/test/features/step_definitions/trash.js
packages/nuxeo-web-ui-ftest/test/pages/ui/results.js
packages/nuxeo-web-ui-ftest/test/pages/ui/selection.js

task-NXP-25345-hardDeleteSelection

---

elements/nuxeo-app.js
ftest/test/features/trash.feature
packages/nuxeo-web-ui-ftest/test/features/step_definitions/browser.js
packages/nuxeo-web-ui-ftest/test/pages/ui/browser.js

task-ELEMENTS-953-hardDeleteNavigate

---

packages/nuxeo-web-ui-ftest/test/pages/ui/browser/document_task.js

fix-ELEMENTS-945-UserContainingNullName

---

addons/nuxeo-spreadsheet/nuxeo-spreadsheet.html
elements/nuxeo-results/nuxeo-results.js

Platform PR for JSF: https://github.com/nuxeo/nuxeo/pull/3094

fix-NXP-26021-DisableSpreadsheetOnTrash

---

elements/nuxeo-document-bulk-actions/nuxeo-add-to-collection-documents-button.html

fix-ELEMENTS-934-selectivity-callers

---

elements/nuxeo-results/nuxeo-document-content.js
elements/nuxeo-results/nuxeo-document-trash-content.js

Related to https://github.com/nuxeo/nuxeo-elements/pull/113

NXP-27555: add filter-expression to document and trash content

---

.eslintignore
.prettierignore
Jenkinsfiles/web-ui-pipeline.groovy
elements/nuxeo-collections/nuxeo-collections.js
packages/nuxeo-web-ui-ftest/package.json
packages/nuxeo-web-ui-ftest/test/features/step_definitions/support/fixtures/layouts.js
packages/nuxeo-web-ui-ftest/test/pages/ui/browser.js
packages/nuxeo-web-ui-ftest/wdio.conf.js

fix-NXP-27317-stabilize-tests

---

elements/nuxeo-cloud-services/nuxeo-tokens-behavior.js
elements/nuxeo-document-creation/nuxeo-document-creation-behavior.js
package.json

Fix nxp 27637 polymer 3.3.0

---

addons/nuxeo-dam/nuxeo-dam.html
elements/document/collection/nuxeo-collection-view-layout.html
elements/document/nuxeo-document-create.js
elements/document/nuxeo-document-form-layout.js
elements/document/nuxeo-document-import.js
elements/nuxeo-app.js
elements/nuxeo-collections/nuxeo-collections.js
elements/nuxeo-web-ui-bundle.html

fix-ELEMENTS-964-maxItemsConfig

---

plugin/web-ui/addon/src/main/resources/OSGI-INF/web-ui-properties.xml

fix-NXP-27651-maxItems

---

elements/nuxeo-app.js

fix-NXP-26692-doc-action

---

elements/nuxeo-app.html

fix-NXP-26692-doc-action-10.10

---

package.json

fix-NXP-27703-elements-version

---

elements/search/nuxeo-results-view.html

fix-NXP-27699-results-view-visible-10.10

---

elements/search/nuxeo-results-view.js

fix-NXP-27699-results-view-visible

---

packages/nuxeo-web-ui-ftest/test/pages/ui/browser/document_task.js

improvement-NXP-27702-AddWorkflowLayoutHelperToWebuiFtest

---

index.html

fix-ELEMENTS-996-form-auth

---

addons/easyshare/elements/nuxeo-easyshare-share-link.js
addons/nuxeo-arender/elements/nuxeo-arender-blob-diff-button.js
addons/nuxeo-drive/elements/nuxeo-drive-edit-button.js
addons/nuxeo-drive/elements/nuxeo-drive-sync-toggle-button.js
addons/nuxeo-spreadsheet/elements/nuxeo-spreadsheet-button.js
addons/nuxeo-template-rendering/elements/nuxeo-delete-template-button.js
addons/nuxeo-template-rendering/elements/nuxeo-render-template-button.js
elements/diff/nuxeo-document-diff-button.js
elements/diff/nuxeo-versions-diff-button.js
elements/nuxeo-collections/nuxeo-collection-move-bottom-action.js
elements/nuxeo-collections/nuxeo-collection-move-down-action.js
elements/nuxeo-collections/nuxeo-collection-move-top-action.js
elements/nuxeo-collections/nuxeo-collection-move-up-action.js
elements/nuxeo-collections/nuxeo-collection-remove-action.js
elements/nuxeo-document-actions/nuxeo-clipboard-toggle-button.js
elements/nuxeo-document-actions/nuxeo-document-form-button.js
elements/nuxeo-document-actions/nuxeo-replace-blob-button.js
elements/nuxeo-document-bulk-actions/nuxeo-add-to-collection-documents-button.js
elements/nuxeo-document-bulk-actions/nuxeo-clipboard-documents-button.js
elements/nuxeo-document-bulk-actions/nuxeo-delete-documents-button.js
elements/nuxeo-document-bulk-actions/nuxeo-untrash-documents-button.js

fix-ELEMENTS-997-tooltips-actions-menu

---

addons/easyshare/elements/nuxeo-easyshare-share-link.js

Related to https://github.com/nuxeo/nuxeo-elements/pull/140

NXP-27799: uniformize share dialog margins

---

elements/nuxeo-results/nuxeo-document-content-behavior.js
elements/nuxeo-results/nuxeo-document-content.js

fix-NXP-27759-orderable-params

---

plugin/web-ui/addon/build.xml

fix-NXP-27833-update-node-version

---

plugin/metrics/wdio.conf.js

task-NXP-27325-metrics-safari

---

addons/nuxeo-ai-core/index.js

Backport 10.10: https://github.com/nuxeo/nuxeo-ai/pull/106

NXP-27879: check if layout contains a document

---

elements/nuxeo-results/nuxeo-results.html

Server Side contribution changes: https://github.com/nuxeo/nuxeo/pull/3277

NXP-26504: spreadsheet available only when columns are defined (Backport 10.10)

---

elements/nuxeo-app.js

ELEMENTS: https://github.com/nuxeo/nuxeo-elements/pull/147

NXP-27710: ensure document refresh after lock operations

---

ftest/test/features/publication.feature
packages/nuxeo-web-ui-ftest/test/pages/ui/browser/document_versions.js
packages/nuxeo-web-ui-ftest/test/pages/ui/browser/publication_dialog.js

Several pipeline runs:
https://qa.nuxeo.org/jenkins/job/web-ui-pipeline-ncunha/221/
https://qa.nuxeo.org/jenkins/job/web-ui-pipeline-gbarata/259/

NXP-27869: activate and stabilize  publishing ftests

---

elements/nuxeo-document-viewer/nuxeo-document-viewer.js

fix-NXP-27829-DuplicatedAuditEntries

---

elements/nuxeo-document-viewer/nuxeo-document-viewer.html

fix-NXP-27829-DuplicatedAuditEntries-10.10 (Backport)

---

elements/nuxeo-document-versions/nuxeo-document-create-version.js

Pipeline: https://qa.nuxeo.org/jenkins/job/web-ui-pipeline-ncunha/223/

NXP-27795: remove unused <nuxeo-document> element

---

elements/nuxeo-document-bulk-actions/nuxeo-add-to-collection-documents-button.js

NXP-27929: UndefinedCollectionId

---

elements/nuxeo-document-bulk-actions/nuxeo-delete-documents-button.js

fix-ELEMENTS-1010-DeleteButtonPermissions

---

addons/easyshare/document/easysharefolder/nuxeo-easysharefolder-view-layout.html
addons/nuxeo-ai-core/elements/admin-ai-core.js
elements/document/collection/nuxeo-collection-view-layout.html
elements/document/favorites/nuxeo-favorites-view-layout.html
elements/document/nuxeo-document-import.js
elements/nuxeo-admin.html
elements/nuxeo-admin/nuxeo-analytics.js
elements/nuxeo-app.js
elements/nuxeo-browser.html
elements/nuxeo-document-blob/nuxeo-document-blob.js
elements/nuxeo-document-create-button/nuxeo-document-create-button.js
elements/nuxeo-document-create-popup/nuxeo-document-create-popup.js
elements/nuxeo-dropzone/nuxeo-dropzone.js
elements/nuxeo-publication/nuxeo-publish-button.js
elements/nuxeo-results/nuxeo-document-trash-content.js
elements/nuxeo-results/nuxeo-results.js
elements/nuxeo-themes.html

Pipeline check: https://qa.nuxeo.org/jenkins/view/All/job/web-ui-pipeline-gbarata/270/

NXP-27954: update nuxeo-slot name attribute

---

elements/document/nuxeo-document-page.html
src/main/resources/OSGI-INF/web-ui-properties.xml

fix-NXP-27963-commentable-10.10

---

packages/nuxeo-web-ui-ftest/test/features/step_definitions/document.js
packages/nuxeo-web-ui-ftest/test/features/step_definitions/support/fixtures/layouts.js

fix-NXP-28027-miscFtest-master

---

elements/document/nuxeo-document-create.js

Pipeline here: https://qa.nuxeo.org/jenkins/job/web-ui-pipeline-ncunha/238/

NXP-27964: ensure suggester is inside scrollable area

---

elements/document/nuxeo-collapsible-document-page.js
elements/nuxeo-results/nuxeo-document-content.js
elements/nuxeo-results/nuxeo-document-trash-content.js
elements/nuxeo-results/nuxeo-results.js
themes/base.js

fix-NXP-27960-cleanup-results-vars

---

elements/nuxeo-document-tree/nuxeo-document-tree.html

Backport from https://github.com/nuxeo/nuxeo-web-ui/pull/730
Pipeline: https://qa2.nuxeo.org/jenkins/job/WebUI/job/web-ui-pipeline-10.10/209 (Known Random Error on edit groups)

NXP-26749: ensure that only folderish docs are shown (Backport 10.10)

---

elements/search/nuxeo-search-form.js

fix-NXP-27722-cleanup-search-form-params

---

elements/search/nuxeo-search-form.html

fix-NXP-27722-cleanup-search-form-params-1010

---

elements/nuxeo-document-actions/nuxeo-clipboard-toggle-button.js
elements/nuxeo-document-bulk-actions/nuxeo-clipboard-documents-button.js
elements/nuxeo-web-ui-bundle.html

fix-NXP-27944-ClipboardRestrictions

---

elements/nuxeo-document-actions/nuxeo-clipboard-toggle-button.html
elements/nuxeo-document-bulk-actions/nuxeo-clipboard-documents-button.html
elements/nuxeo-web-ui-bundle.html

fix-NXP-27944-ClipboardRestrictions-10.10

---

elements/nuxeo-document-actions/nuxeo-clipboard-toggle-button.html
elements/nuxeo-document-bulk-actions/nuxeo-clipboard-documents-button.html
elements/nuxeo-web-ui-bundle.html

fix-NXP-27944-ClipboardRestrictions-9.10

---

addons/easyshare/document/easysharefolder/nuxeo-easysharefolder-view-layout.html
elements/document/collection/nuxeo-collection-view-layout.html
elements/document/favorites/nuxeo-favorites-view-layout.html
elements/nuxeo-web-ui-bundle.html

fix-NXP-27828-RestoreCollectionSlot

---

elements/nuxeo-publication/nuxeo-publication-info-bar.html

NXP-28147: add document to infoLabel on publication-info-bar (Backport 10.10)

---

elements/nuxeo-publication/nuxeo-publication-info-bar.js

NXP-28147: add document to infoLabel on publication-info-bar

---

elements/nuxeo-tasks.html

NXP-27946: fix div sizes on nuxeo-tasks

---

elements/document/collection/nuxeo-collection-view-layout.html
elements/document/favorites/nuxeo-favorites-view-layout.html

fix-NXP-27955-updateCollectionsSlotsSyntax-10.10

---

elements/nuxeo-app.js

fix-NXP-28076-changeDrawerDisplayToFlex

---

elements/search/nuxeo-results-view.html

fix-NXP-28268-pageSearch-10.10

---

elements/search/nuxeo-results-view.js

fix-NXP-28268-pageSearch

---

addons/nuxeo-csv/ftest/features/csv-import.feature
addons/nuxeo-csv/ftest/features/step_definitions/csv-import.js
addons/nuxeo-csv/ftest/resources/csv-import-sample.csv
ftest/itests.xml
ftest/pom.xml
packages/nuxeo-web-ui-ftest/pages/ui/create_dialog.js

https://qa.nuxeo.org/jenkins/view/TestAndPush/job/web-ui-pipeline-fdsantos/59/console 🎉

NXP-27968: create CSV import ftest

---

addons/nuxeo-drive/elements/nuxeo-drive-desktop-packages.js
i18n/messages-ar.json
i18n/messages-de.json
i18n/messages-es-ES.json
i18n/messages-eu.json
i18n/messages-fr.json
i18n/messages-he.json
i18n/messages-id.json
i18n/messages-it.json
i18n/messages-ja.json
i18n/messages-nl.json
i18n/messages-pt-PT.json
i18n/messages-sv-SE.json
i18n/messages-zh-CN.json
i18n/messages.json

I also alphabetically sorted links.

NXP-28051: Update Nuxeo Drive link for GNU/Linux binary

---

packages/nuxeo-web-ui-ftest/features/step_definitions/search.js
packages/nuxeo-web-ui-ftest/pages/ui/results.js

https://qa.nuxeo.org/jenkins/view/TestAndPush/job/web-ui-pipeline-fdsantos/65/

NXP-27242: fix searching for 0 results

---

ftest/features/admin.feature
packages/nuxeo-web-ui-ftest/features/step_definitions/admin.js
packages/nuxeo-web-ui-ftest/pages/ui/administration.js

task-NXP-28300-nxqlSearchTest

---

addons/nuxeo-dam/document/audio/nuxeo-audio-create-layout.html
addons/nuxeo-dam/document/picture/nuxeo-picture-create-layout.html
addons/nuxeo-dam/document/video/nuxeo-video-create-layout.html
addons/nuxeo-platform-3d/elements/nuxeo-3d-preview.js
addons/nuxeo-template-rendering/document/templatesource/nuxeo-templatesource-create-layout.html
elements/document/file/nuxeo-file-create-layout.html
elements/nuxeo-document-actions/nuxeo-replace-blob-button.js
elements/nuxeo-document-attachments/nuxeo-document-attachments.js
elements/nuxeo-document-viewer/nuxeo-document-viewer.js
elements/nuxeo-dropzone/nuxeo-dropzone.js

Probably I'll squash both commits with the message on the title!

NXP-28263: dropzone handling tasks

---

elements/nuxeo-clipboard/nuxeo-clipboard.html

NXP-28312: remove data list min-height in nuxeo-clipboard

NXP-28312 10.10 backport

---

themes/base.js

Related to: https://github.com/nuxeo/nuxeo-elements/pull/186

NXP-28337: add nuxeo secondary button default style

---

addons/nuxeo-drive/elements/nuxeo-drive-sync-toggle-button.js

Backport 10.10: https://github.com/nuxeo/nuxeo/pull/3593

NXP-28167: drive sync button available for collection facet

---

elements/nuxeo-tasks.html

fix-NXP-27946-DivSizesOnNuxeoTasks-10.10

---

addons/nuxeo-dam/elements/nuxeo-picture-formats.js

fix-NXP-28172-changeDimensionsValuesOnNuxeoDAM

---

elements/nuxeo-admin/nuxeo-user-group-management-page.js
elements/routing.js
ftest/features/group.feature
ftest/features/user.feature
packages/nuxeo-web-ui-ftest/features/step_definitions/group.js
packages/nuxeo-web-ui-ftest/features/step_definitions/user.js
packages/nuxeo-web-ui-ftest/pages/base.js

fix-NXP-27994-encode-users-groups

---

elements/nuxeo-admin/nuxeo-user-group-management-page.html
elements/routing.html

fix-NXP-27994-encode-users-groups-1010

---

elements/nuxeo-app.html
elements/search/nuxeo-search-form.html

fix-NXP-28117-spreadsheet-refresh-10.10

---

packages/nuxeo-web-ui-ftest/features/step_definitions/support/fixtures/layouts.js

Make the selectivity setter helper to clear value before setting a new one on single value mode

NXP-26890: make the selectivity setter helper to clear value in single mode

---

elements/nuxeo-document-attachments/nuxeo-document-attachments.html
elements/nuxeo-dropzone/nuxeo-dropzone.html

fix-NXP-28363-updateDocumentOnUploadBlob

---

elements/nuxeo-collections/nuxeo-collections.js
elements/nuxeo-document-bulk-actions/nuxeo-add-to-collection-documents-button.js

Pipeline: https://qa.nuxeo.org/jenkins/job/web-ui-pipeline-ncunha/258/

fix-NXP-27163-HandlingMyFavoritesCollection

---

elements/nuxeo-collections/nuxeo-collections.html
elements/nuxeo-document-bulk-actions/nuxeo-add-to-collection-documents-button.html

Pipeline: https://qa2.nuxeo.org/jenkins/job/WebUI/job/web-ui-pipeline-10.10/359/

fix-NXP-27163-HandlingMyFavoritesCollection-10.10 (Backport)

---

elements/nuxeo-app.js

fix-NXP-28525-fixNuxeoAppZindex

---

addons/nuxeo-drive/elements/nuxeo-drive-edit-button.js

fix-NXP-28497-disableDirectEditIfProxy

---

elements/nuxeo-app.js
elements/nuxeo-document-bulk-actions/nuxeo-download-documents-button.js

fix-NXP-28478-showProgressOnBulkDownload

---

elements/nuxeo-app.html
elements/nuxeo-document-bulk-actions/nuxeo-download-documents-button.html

fix-NXP-28478-showProgressOnBulkDownload-10.10

---

elements/document/nuxeo-document-import.html
elements/nuxeo-document-creation/nuxeo-document-creation-behavior.html

Backport of nuxeo/nuxeo-web-ui#816.

NXP-28495: lock import controls while document is being initialized (10.10)

---

i18n/messages.json

PR created from https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-grenard-10.10/18/

fix-NXP-28552-retentionAudit

---

elements/nuxeo-document-actions/nuxeo-clipboard-toggle-button.js
elements/nuxeo-document-bulk-actions/nuxeo-clipboard-documents-button.js

fix-NXP-27835-DisableClipboardForProxies

---

elements/nuxeo-document-actions/nuxeo-clipboard-toggle-button.html
elements/nuxeo-document-bulk-actions/nuxeo-clipboard-documents-button.html

fix-NXP-27835-DisableClipboardForProxies-10.10

---

elements/nuxeo-app.html

🔵 Pipeline: https://qa2.nuxeo.org/jenkins/job/WebUI/job/web-ui-pipeline-10.10/376/

NXP-27823: ensure configuration is interpreted as boolean

---

ftest/features/metadata.feature
ftest/features/trash.feature
packages/nuxeo-web-ui-ftest/features/step_definitions/browser.js
packages/nuxeo-web-ui-ftest/features/step_definitions/comments.js
packages/nuxeo-web-ui-ftest/features/step_definitions/create_dialog.js
packages/nuxeo-web-ui-ftest/features/step_definitions/document.js
packages/nuxeo-web-ui-ftest/features/step_definitions/tasks.js
packages/nuxeo-web-ui-ftest/features/step_definitions/ui.js
packages/nuxeo-web-ui-ftest/pages/ui.js
packages/nuxeo-web-ui-ftest/pages/ui/browser.js
packages/nuxeo-web-ui-ftest/pages/ui/browser/document_versions.js
packages/nuxeo-web-ui-ftest/pages/ui/browser/publication_dialog.js

fix-NXP-28737-stab-ftests

---

elements/nuxeo-document-creation/nuxeo-document-creation-behavior.js

fix-NXP-28047-AiModelsEnricherOnCreation

---

elements/nuxeo-document-creation/nuxeo-document-creation-behavior.html

fix-NXP-28047-AiModelsEnricherOnCreation-10.10

---

packages/nuxeo-web-ui-ftest/pages/ui/drawer.js

improvement-NXP-28756-checkDrawerState

---

elements/nuxeo-app.html
elements/search/nuxeo-search-form.html

fix-NXP-24967-saved-search-doc-url-10.10

---

elements/nuxeo-app.html
elements/search/nuxeo-search-form.html

fix-NXP-24967-saved-search-doc-url-9.10

---

elements/nuxeo-document-versions/nuxeo-document-create-version.html
elements/nuxeo-restore-version-button/nuxeo-restore-version-button.html

task-NXP-28644-VersionningAndRetetention-10.10

---

elements/document/nuxeo-document-create.html
elements/nuxeo-document-creation/nuxeo-document-creation-behavior.html
i18n/messages.json

This Pull Request looks good!
PR created from: https://qa2.nuxeo.org/jenkins/job/WebUI/job/web-ui-pipeline-10.10/387/
New PR OK (rebasing on 10.10): https://qa2.nuxeo.org/jenkins/job/WebUI/job/web-ui-pipeline-10.10/388/

10.10-HF/fix-NXP-28662-Trashed-folder-allows-document-creation

---

ftest/itests.xml
ftest/pom.xml
plugin/itests/addon/src/main/resources/OSGI-INF/extensions.xml
plugin/itests/addon/src/main/resources/data/schemas/files.xsd
plugin/itests/marketplace/src/main/assemble/assembly.xml

Platform PR: https://github.com/nuxeo/nuxeo/pull/3832

NXP-28000: add missing dependency and correct package name

---

elements/document/nuxeo-document-create.js
elements/nuxeo-document-creation/nuxeo-document-creation-behavior.js
i18n/messages.json

T&P In Progress: https://qa.nuxeo.org/jenkins/job/master/job/web-ui-saouana/1/
T&P will be relaunched once the functional tests issue fixed (related on stuff to fix `pom.xml`, `assembly.xml`...
new T&P after rebasing the master [PR](https://github.com/nuxeo/nuxeo-web-ui/pull/853)  is now merged into master 
https://qa.nuxeo.org/jenkins/job/master/job/web-ui-saouana/2/ -> OK

NXP-28662: Trashed folder allows document creation

---

elements/search/nuxeo-search-form.html

fix-NXP-27429-fixAbsolutePositionOnMobileBrowsers-10.10

---

elements/search/nuxeo-search-form.html

fix-NXP-27429-fixAbsolutePositionOnMobileBrowsers-9.10

---

elements/nuxeo-document-history/nuxeo-document-history.html

Backport of https://github.com/nuxeo/nuxeo-web-ui/pull/858

NXP-28785: compare audit comment using regex (Backport 10.10)

---

elements/nuxeo-dropzone/nuxeo-dropzone.html

The problem: 
All the info on the [ticket](https://jira.nuxeo.com/browse/NXP-28827).

NXP-28827: bind multiple attribute to blob-list in dropzone (proposal)

---

elements/nuxeo-results/nuxeo-document-content-behavior.js

fix-NXP-28733-document-content-sort-params

---

elements/nuxeo-results/nuxeo-document-content-behavior.html

fix-NXP-28733-document-content-sort-params-10.10

---

addons/nuxeo-retention/nuxeo-retention.html
addons/nuxeo-retention/search/retention/nuxeo-retention-search-form.html

T&P In Progress: https://qa.nuxeo.org/jenkins/job/master/job/web-ui-saouana/3/
the related platform PR is: https://github.com/nuxeo/nuxeo/pull/3923

NXP-28885: fix retention search

---

elements/document/nuxeo-document-import.js

fix-NXP-28934-import-path

---

elements/document/nuxeo-document-import.js

T&P In Progress: https://qa.nuxeo.org/jenkins/job/master/job/web-ui-saouana/4/ 
element related PR: https://github.com/nuxeo/nuxeo-elements/pull/229

NXP-28812: fix cancelation on multipart upload

---

elements/document/nuxeo-document-import.js

Fix related to the build failure: https://qa.nuxeo.org/jenkins/blue/organizations/jenkins/master%2Fplugins_nuxeo-web-ui-master-master/detail/plugins_nuxeo-web-ui-master-master/4105/changes/
and 
```
elements/document/nuxeo-document-import.js
↑↑ these files are not prettier formatted ↑↑
```
T&P: https://qa.nuxeo.org/jenkins/job/master/job/web-ui-saouana/6/

NXP-28812: fix the wrong formatting

---

i18n/messages.json

Backport from https://github.com/nuxeo/nuxeo-web-ui/pull/886

NXP-28810: add retention rule type label (Backport)

---

addons/nuxeo-retention/search/retention/nuxeo-retention-search-results.html

Try  to fix the failed Jenkins build https://qa.nuxeo.org/jenkins/job/master/job/plugins_nuxeo-web-ui-master-master/
and the Jira ticket: https://jira.nuxeo.com/browse/NXP-28804
T&P In Progress: https://qa.nuxeo.org/jenkins/job/master/job/web-ui-saouana-2/1/

NXP-28804: fix wrong lint formatter

---

package.json

Run without selection issues: https://qa.nuxeo.org/jenkins/job/web-ui-pipeline-ncunha/342/
But since one test failed (hopefully a random one) there is other run [ongoing](https://qa.nuxeo.org/jenkins/job/web-ui-pipeline-ncunha/344/)

NXP-29030: lock polymer dependency

---

addons/easyshare/document/easysharefolder/nuxeo-easysharefolder-view-layout.html
elements/document/collection/nuxeo-collection-view-layout.html
elements/document/favorites/nuxeo-favorites-view-layout.html
elements/nuxeo-results/nuxeo-document-trash-content.js
elements/nuxeo-results/nuxeo-results.js
elements/search/trash/nuxeo-trash-search-results.html

T&P https://qa.nuxeo.org/jenkins/job/Other/job/web-ui-pipeline-nsilva/153

NXP-28977: avoid native slots in nuxeo-actions-menu

---

elements/nuxeo-admin/nuxeo-audit.html
elements/nuxeo-document-history/nuxeo-document-history.html

NXP-28862: modify date format to show time for nuxeo document history and audit (Backport 10.10)

---

packages/nuxeo-web-ui-ftest/scripts/specs-processor.js
packages/nuxeo-web-ui-ftest/scripts/test.js

Pipeline 🔵 
https://qa.nuxeo.org/jenkins/view/TestAndPush/job/web-ui-pipeline-ncunha/346/

NXP-29060: adapt specs processor to use location argument

---

elements/nuxeo-app.js
elements/nuxeo-document-bulk-actions/nuxeo-untrash-documents-button.js

fix-NXP-28902-CollectionsDeleteRefresh

---

elements/nuxeo-app.html
elements/nuxeo-document-bulk-actions/nuxeo-untrash-documents-button.html

fix-NXP-28902-CollectionsDeleteRefresh-10.10

---

elements/nuxeo-browser.html

fix-NXP-28353-overflowInNuxeoActionsMenuDiv-10.10

---

elements/nuxeo-browser.html
packages/nuxeo-web-ui-ftest/pages/ui/browser.js

fix-NXP-28353-overflowInNuxeoActionsMenuDiv

---

elements/nuxeo-admin/nuxeo-workflow-analytics.html

NXP-28338: show translated taskName instead of action in workflow analytics (9.10)

---

elements/search/nuxeo-search-form.js

Seems to be alright in 10.10 and 9.10

NXP-29211: add missing function binding

---

addons/amazon-s3-online-storage/index.js
elements/document/nuxeo-document-import.js
elements/nuxeo-dropzone/nuxeo-dropzone.js
i18n/messages.json

Aggregates:
#916
#917
#918
#919
#920

NXP-29129: fix Web UI upload error handling

---

elements/nuxeo-collections/nuxeo-collection-remove-action.html

T&P at https://qa2.nuxeo.org/jenkins/job/WebUI/job/web-ui-pipeline-9.10/335/

NXP-28775: use document id to send a stateless document

---

elements/document/nuxeo-document-import.html
elements/nuxeo-dropzone/nuxeo-dropzone.html
i18n/messages-ar.json
i18n/messages-de.json
i18n/messages-es-ES.json
i18n/messages-eu.json
i18n/messages-fr.json
i18n/messages-he.json
i18n/messages-id.json
i18n/messages-it.json
i18n/messages-ja.json
i18n/messages-nl.json
i18n/messages-pt-PT.json
i18n/messages-sv-SE.json
i18n/messages-zh-CN.json
i18n/messages.json

Depends on:
- nuxeo/nuxeo-ui-elements#483
- nuxeo/nuxeo#4175

Fix nxp 28980 show upload errors 10.10

---

index.html
plugin/web-ui/addon/src/main/resources/OSGI-INF/web-ui-properties.xml

Depends on https://github.com/nuxeo/nuxeo/tree/fix-NXP-29325-blob-preview

NXP-29325: use blob embed preview when available

---

elements/nuxeo-app.html
elements/nuxeo-document-bulk-actions/nuxeo-untrash-documents-button.html

And ensure consistency on untrash event payload

NXP-29365: refresh collections view when deleting collection doctype

---

elements/workflow/nuxeo-document-task-assignment-popup.html

PR created from https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-pabgrall-10.10/5/

fix-NXP-29347-nuxeo-document-task-assignment-popup-outputs-comment-1010

---

elements/nuxeo-app.html

Backport of #964.
🔵 https://qa2.nuxeo.org/jenkins/job/WebUI/job/web-ui-pipeline-10.10/458/console

NXP-29210: rely on the current document id if available (10.10)

---

Jenkinsfiles/web-ui-pipeline.groovy
package.json

Related to nuxeo/nuxeo-elements#265.

NXP-29288: align on custom versions for forked dependencies

---

elements/nuxeo-app.html

NXP-28972: handle 403 error after task completion (10.10)

---

elements/nuxeo-admin/nuxeo-search-analytics.html

NXP-29201: fix analytics search tab not refreshing (10.10)

---

elements/elements.html
elements/nuxeo-app.html
elements/nuxeo-browser.html
elements/nuxeo-browser/nuxeo-repositories.html
elements/nuxeo-home.html
src/main/resources/OSGI-INF/auth-config.xml
src/main/resources/OSGI-INF/deployment-fragment.xml
src/main/resources/web/nuxeo.war/ui/index.jsp

fix-NXP-29331-headless-repository-10.10

---

elements/nuxeo-data-grid/nuxeo-document-grid-thumbnail.html
elements/nuxeo-results/nuxeo-results.html

fix-NXP-28791-perf-910

---

elements/routing.html

WEBUI-25: fix Web UI not loading on Edge Legacy (10.10)

---

elements/nuxeo-document-actions/nuxeo-document-form-button.html

WEBUI-20: Use WriteProperties permission in nuxeo-document-form-button

---

elements/nuxeo-clipboard/nuxeo-clipboard.html

Backport of the https://github.com/nuxeo/nuxeo-web-ui/pull/1010.

WEBUI-41: refresh clipboard based on content update 10.10

---

elements/document/nuxeo-document-create.html
elements/nuxeo-document-create-popup/nuxeo-document-create-popup.html

WEBUI-42: init and clear create popup dialog 10.10

---

elements/nuxeo-document-create-button/nuxeo-document-create-button.html
elements/nuxeo-document-creation/nuxeo-document-creation-behavior.html

WEBUI-36: use AddChildren instead of Write permission (10.10)

---

elements/document/nuxeo-collapsible-document-page.html
elements/nuxeo-document-actions/nuxeo-replace-blob-button.html
elements/nuxeo-document-attachments/nuxeo-document-attachments.html
elements/nuxeo-document-viewer/nuxeo-document-viewer.html
elements/nuxeo-note-editor/nuxeo-note-editor.html
elements/search/nuxeo-saved-search-actions.html

Backport of #998. Will update with a pipeline run ASAP.

WEBUI-21: Update Web UI elements to use WriteProperties permission (10.10)

---

elements/nuxeo-collections/nuxeo-collection-remove-action.html

fix-NXP-29645-es-sync-index-on-collection-9.10

---

elements/nuxeo-results/nuxeo-results.html

Pipeline running https://qa2.nuxeo.org/jenkins/job/WebUI/job/web-ui-pipeline-10.10/521/
This is the backport for WEBUI-44 in master.

WEBUI-44: enqueue debounce to prevent request cancelling 10.10

---

elements/nuxeo-collections/nuxeo-collection-remove-action.html

fix-NXP-29645-es-sync-index-on-collection-10.10

---

addons/amazon-s3-online-storage/index.js

Let me know if this is understandable...

NXP-29577: sequence s3 uploads to prevent clock skew

---

elements/nuxeo-app.html

fix-WEBUI-22-backportDrawerStyle

---

themes/loader.html

fix-WEBUI-65-theme-loading

---

elements/nuxeo-collections/nuxeo-collection-remove-action.js

fix-NXP-29645-es-sync-index-on-collection-master

---

sw.js

🔵  https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-nsilva-10.10/26/

WEBUI-86: bypass service worker for API requests

---

elements/search/nuxeo-search-form.html

WEBUI-23: avoid resetting array params on splice/length events (10.10)

---

elements/workflow/nuxeo-document-task.html
i18n/messages.json

fix-NXP-28080-TasksInEndState-10.10 (Backport 10.10)

---

elements/nuxeo-clipboard/nuxeo-clipboard.html

Backporting work done by @richardsd (https://jira.nuxeo.com/browse/WEBUI-41) to 9.10.

WEBUI-93: refresh clipboard based on content update (Backport 9.10)

---

elements/search/nuxeo-search-form.html

My proposal is to add again the parse in the fetch method.

NXP-28554: fix saved sarches saving

---

elements/search/nuxeo-search-form.html

NXP-28554: fix element linting

---

elements/nuxeo-results/nuxeo-results.html

🔵  Pipeline: https://qa2.nuxeo.org/jenkins/job/WebUI/job/web-ui-pipeline-10.10/597/

WEBUI-87: listen to subproperty and mutation changes (Backport 10.10)

---

elements/search/nuxeo-search-form.html

WEBUI-64: prevent triggering search when form is invalid (10.10)

---

i18n/messages.json

Fix-WEBUI-114-Add-ReadWrite-Translation

---

.github/workflows/promote.yaml

Related https://github.com/nuxeo/nuxeo-elements/pull/322.
As a bonus, also creating a github release.

WEBUI-96: allow promotion.yaml to accept ref branch and dry run as input 

---

elements/nuxeo-document-viewer/nuxeo-document-viewer.html

Fix for Jira Issue: https://jira.nuxeo.com/browse/WEBUI-71
Test And Push[In Progress]: https://qa2.nuxeo.org/jenkins/job/WebUI/job/web-ui-pipeline-9.10/422/

WEBUI-71: Hide dropzone for read-only users

---

index.js

Depends on https://github.com/nuxeo/nuxeo-elements/pull/330

WEBUI-151: use importHTML to load the main bundle

---

elements/nuxeo-document-versions/nuxeo-document-versions.js
pom.xml

Backport of https://github.com/nuxeo/nuxeo-web-ui/pull/1114.

WEBUI-162: fix show latest version

---

elements/nuxeo-document-creation/nuxeo-document-creation-behavior.js

The solution for now is to revert this commit as it is causing problems on several demos, and possibly affecting customer projects.
However, the drawback is a slight flicker on the document create and import layouts when initializing the documents, which can be particularly problematic depending on how much time it takes for the server to return the result of the document initialization (therefore amplified by lengthy computations associated with the "Empty Document Created" event and/or network congestion). A dedicated ticket will be created to address this properly.

WEBUI-134: revert caching that invalidates the Empty Document Created event handler

---

elements/nuxeo-document-creation/nuxeo-document-creation-behavior.js

WEBUI-134: revert caching that invalidates the Empty Document Created event handler (3.0.x)

---

elements/nuxeo-document-creation/nuxeo-document-creation-behavior.html

WEBUI-134: revert caching that invalidates the Empty Document Created event handler (10.10)

---

README.md
package.json
packages/nuxeo-web-ui-ftest/package.json

Analogous to [nuxeo-elements/pull/351](https://github.com/nuxeo/nuxeo-elements/pull/351).

WEBUI-183: update node requirements

---

README.md
package.json
packages/nuxeo-web-ui-ftest/package.json

Backport of [nuxeo-web-ui/pull/1130](https://github.com/nuxeo/nuxeo-web-ui/pull/1130).

WEBUI-183: update node requirements (3.0.x)

---

README.md
package.json

Backport of [nuxeo-web-ui/pull/1130](https://github.com/nuxeo/nuxeo-web-ui/pull/1130).

WEBUI-183: update node requirements (10.10)

---

README.md
package.json

Backport of [nuxeo-web-ui/pull/1130](https://github.com/nuxeo/nuxeo-web-ui/pull/1130).

WEBUI-183: update node requirements (9.10)

---

elements/diff/nuxeo-diff.html
elements/document/nuxeo-document-import.html
elements/nuxeo-app.html
elements/nuxeo-collections/nuxeo-collections.html
elements/nuxeo-document-comments/nuxeo-document-comment-thread.html
elements/nuxeo-document-creation/nuxeo-document-creation-behavior.html
elements/nuxeo-document-info-bar/nuxeo-document-info-bar.html
elements/nuxeo-home.html
elements/nuxeo-publication/nuxeo-document-publications.html
elements/nuxeo-results/nuxeo-document-content.html
elements/nuxeo-results/nuxeo-document-trash-content.html
elements/nuxeo-tasks.html
elements/search/nuxeo-results-view.html
elements/search/nuxeo-search-form.html

PR created from https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-pabgrall-10.10/9/

fix-ELEMENTS-1307-do-not-use-dots-in-HTTP-headers

---

gulpfile.js

WEBUI-239: Avoid running babel on pdf.worker.js

---

elements/nuxeo-grid/nuxeo-grid.js

Backport of https://github.com/nuxeo/nuxeo-web-ui/pull/1149

WEBUI-171: update nuxeo grid desc 3.0.x

---

elements/nuxeo-app.js
elements/nuxeo-app/nuxeo-expired-session.js
elements/nuxeo-app/nuxeo-offline-banner.js
elements/nuxeo-app/nuxeo-page.js
elements/nuxeo-selection/nuxeo-selection-toolbar.js
elements/nuxeo-suggester/nuxeo-suggester.js
elements/nuxeo-tasks/nuxeo-tasks-list.js
elements/search/nuxeo-search-form.js

WEBUI-181: adjust elements to nuxeo-app-top

---

elements/nuxeo-app.js
elements/nuxeo-app/nuxeo-expired-session.js
elements/nuxeo-app/nuxeo-offline-banner.js
elements/nuxeo-app/nuxeo-page.js
elements/nuxeo-selection/nuxeo-selection-toolbar.js
elements/nuxeo-suggester/nuxeo-suggester.js
elements/nuxeo-tasks/nuxeo-tasks-list.js
elements/search/nuxeo-search-form.js

backport of https://github.com/nuxeo/nuxeo-web-ui/pull/1148

WEBUI-181: adjust elements to nuxeo-app-top 3.0.x

---

elements/nuxeo-app.html
elements/nuxeo-app/nuxeo-expired-session.html
elements/nuxeo-app/nuxeo-offline-banner.html
elements/nuxeo-app/nuxeo-page.html
elements/nuxeo-selection/nuxeo-selection-toolbar.html
elements/nuxeo-suggester/nuxeo-suggester.html
elements/nuxeo-tasks/nuxeo-tasks-list.html
elements/search/nuxeo-search-form.html

backport of https://github.com/nuxeo/nuxeo-web-ui/pull/1148

WEBUI-181: adjust elements to  nuxeo-app-top 10.10

---

elements/nuxeo-app.html

Based on the work done by @semisse in [NXP-28076](https://jira.nuxeo.com/browse/NXP-28076). It happens only on 10.10 (tested both on 3.0.x and master).

WEBUI-234: fix drawer scroll overflow

---

elements/directory/l10nxvocabulary/nuxeo-l10nxvocabulary-edit-layout.html

Backport of https://github.com/nuxeo/nuxeo-web-ui/pull/1155

WEBUI-232: subtopic creation hierarchical vocab 10.10

---

elements/nuxeo-collections/nuxeo-collection-remove-action.html

Backport of https://github.com/nuxeo/nuxeo-web-ui/pull/1168

WEBUI-132: enable remove from collection button when user has WriteProperties - 10.10

---

elements/nuxeo-collections/nuxeo-collection-remove-action.js

Backport of https://github.com/nuxeo/nuxeo-web-ui/pull/1168

WEBUI-132: enable remove from collection button when user has WriteProperties - 3.0.x

---

elements/nuxeo-admin/nuxeo-repository-analytics.js
elements/nuxeo-admin/nuxeo-search-analytics.js
elements/nuxeo-admin/nuxeo-workflow-analytics.js
package.json

will also need to update charts-elements dependency version once nuxeo/chart-elements#4 is merged and a new version is generated.

WEBUI-251: remove options from pie chart since equal to default

---

addons/nuxeo-liveconnect/index.js

Backport of https://github.com/nuxeo/nuxeo-web-ui/pull/1189 to 3.0.x.

WEBUI-290: expose Nuxeo.LiveConnectBehavior

---

elements/nuxeo-app.js

This reverts commit 9b6799931863115ff20bfe93b4199dd9e50c4057.

Revert "WEBUI-147: document-updated in tasks navigates to tasks"

---

index.html
polymer.json
src/main/resources/OSGI-INF/web-ui-properties.xml
src/main/resources/web/nuxeo.war/ui/index.jsp

Depends on https://github.com/nuxeo/nuxeo-ui-elements/pull/527
🔵  https://qa2.nuxeo.org/jenkins/job/WebUI/job/web-ui-pipeline-10.10/749/

WEBUI-291: introduce html editor flag

---

elements/nuxeo-publication/nuxeo-publication-info-bar.js

Backport of https://github.com/nuxeo/nuxeo-web-ui/pull/1195.

WEBUI-297: fix publication source URL

---

webpack.config.js

Depends on https://github.com/nuxeo/nuxeo-elements/pull/397

WEBUI-309: use non minified version of Quill

---

elements/nuxeo-admin/nuxeo-distribution-analytics.js
elements/nuxeo-admin/nuxeo-repository-analytics.js
elements/nuxeo-admin/nuxeo-search-analytics.js
elements/nuxeo-admin/nuxeo-workflow-analytics.js
elements/nuxeo-audit/nuxeo-audit-search.js

This is a basic solution using dom-if's to prevent the analytics pages from performing ES requests.

WEBUI-285: lazy load analytics pages upon visibility

---

elements/nuxeo-admin/nuxeo-distribution-analytics.js
elements/nuxeo-audit/nuxeo-audit-search.js

WEBUI-324: fix analytics elements display - 3.0.x

---

elements/nuxeo-admin/nuxeo-distribution-analytics.js
elements/nuxeo-audit/nuxeo-audit-search.js

WEBUI-324: fix analytics elements display

---

plugin/web-ui/addon/src/main/resources/OSGI-INF/page-providers-contrib.xml

WEBUI-329: Add unique component name in the page provider contrib (3.0.x)

---

.github/workflows/promote.yaml
Jenkinsfile
plugin/web-ui/marketplace/pom.xml
plugin/web-ui/marketplace/src/main/assemble/assembly.xml

Backport of https://github.com/nuxeo/nuxeo-web-ui/pull/1106.

WEBUI-140: pad package prerelease with zeros (3.0.x)

---

addons/easyshare/elements/nuxeo-easyshare-share-link.js
addons/nuxeo-platform-3d/elements/nuxeo-3d-preview.js
addons/nuxeo-template-rendering/elements/nuxeo-render-template-button.js
elements/diff/nuxeo-versions-diff-button.js
elements/directory/nuxeo-vocabulary-management.js
elements/document/nuxeo-document-create.js
elements/document/nuxeo-document-form-layout.js
elements/document/nuxeo-document-import.js
elements/nuxeo-cloud-services/nuxeo-cloud-consumers.js
elements/nuxeo-cloud-services/nuxeo-cloud-providers.js
elements/nuxeo-cloud-services/nuxeo-tokens-behavior.js
elements/nuxeo-csv-export/nuxeo-csv-export-button.js
elements/nuxeo-document-attachments/nuxeo-document-attachments.js
elements/nuxeo-document-bulk-actions/nuxeo-download-documents-button.js
elements/nuxeo-document-create-popup/nuxeo-document-create-popup.js
elements/nuxeo-document-viewer/nuxeo-document-viewer.js
elements/nuxeo-dropzone/nuxeo-dropzone.js
elements/nuxeo-note-editor/nuxeo-note-editor.js
elements/nuxeo-publication/nuxeo-document-publications.js
elements/nuxeo-publication/nuxeo-internal-publish.js
elements/nuxeo-publication/nuxeo-unpublish-button.js
elements/nuxeo-results/nuxeo-document-content-behavior.js
elements/nuxeo-results/nuxeo-document-trash-content.js
elements/nuxeo-user-authorized-apps.html
elements/nuxeo-workflow-graph/nuxeo-workflow-graph.js
elements/search/nuxeo-search-form.js
elements/workflow/nuxeo-document-task.js
index.js

Backport of https://github.com/nuxeo/nuxeo-web-ui/pull/1229 for 3.0.x.
Depends on https://github.com/nuxeo/nuxeo-elements/pull/420.

WEBUI-345: make nuxeo-app the fallback notification target (3.0.x)

---

elements/nuxeo-admin/nuxeo-distribution-analytics.js
i18n/messages.json
index.html
plugin/web-ui/addon/src/main/resources/OSGI-INF/web-ui-properties.xml

Backport of https://github.com/nuxeo/nuxeo-web-ui/pull/1192

WEBUI-136: conditionally disable nuxeo-distribution-analytics with user defined threshold

---

packages/nuxeo-web-ui-ftest/features/step_definitions/clipboard.js
packages/nuxeo-web-ui-ftest/features/step_definitions/support/fixtures/layouts.js
packages/nuxeo-web-ui-ftest/pages/ui/browser.js
packages/nuxeo-web-ui-ftest/pages/ui/browser/collapsible_document_page.js

Backport of https://github.com/nuxeo/nuxeo-web-ui/pull/1242 to 3.0.x.

WEBUI-360: fix getAttribute checks (3.0.x)

---

i18n/messages-ar.json
i18n/messages-de.json
i18n/messages-es-ES.json
i18n/messages-eu.json
i18n/messages-fr.json
i18n/messages-he.json
i18n/messages-id.json
i18n/messages-it.json
i18n/messages-ja.json
i18n/messages-nl.json
i18n/messages-pl.json
i18n/messages-pt-PT.json
i18n/messages-sv-SE.json
i18n/messages-zh-CN.json

Backport of the automatic translations from master

WEBUI-136: add translations - 3.0.x

---

packages/nuxeo-web-ui-ftest/pages/ui/note_editor.js

Backport of https://github.com/nuxeo/nuxeo-web-ui/pull/1244.

WEBUI-360: fix get innerHTML in note ftests (3.0.x)

---

elements/nuxeo-suggester/nuxeo-suggester.html

10.10-HF/fix-WEBUI-355-backport-NXP-29177

---

elements/nuxeo-app.js
elements/nuxeo-document-creation/nuxeo-document-creation-behavior.js
elements/nuxeo-document-versions/nuxeo-document-versions.js
elements/nuxeo-dropzone/nuxeo-dropzone.js
elements/nuxeo-publication/nuxeo-publication-info-bar.js
elements/nuxeo-restore-version-button/nuxeo-restore-version-button.js
ftest/features/versions.feature
index.js
legacy.js
packages/nuxeo-web-ui-ftest/features/step_definitions/browser.js
packages/nuxeo-web-ui-ftest/features/step_definitions/document.js
packages/nuxeo-web-ui-ftest/features/step_definitions/login.js
packages/nuxeo-web-ui-ftest/features/step_definitions/search.js
packages/nuxeo-web-ui-ftest/features/step_definitions/support/ui_config.js
packages/nuxeo-web-ui-ftest/pages/helpers.js
packages/nuxeo-web-ui-ftest/pages/ui.js
packages/nuxeo-web-ui-ftest/pages/ui/administration.js
packages/nuxeo-web-ui-ftest/pages/ui/browser.js
packages/nuxeo-web-ui-ftest/pages/ui/browser/collapsible_document_page.js

Backport of https://github.com/nuxeo/nuxeo-web-ui/pull/1218 for 3.0.x.
Depends on https://github.com/nuxeo/nuxeo-elements/pull/425.

WEBUI-333: set ui config from functional tests (3.0.x)

---

elements/search/nuxeo-results-view.html

For master and 3.0.x see https://github.com/nuxeo/nuxeo-elements/pull/443 and https://github.com/nuxeo/nuxeo-elements/pull/442

WEBUI-417: change headers property type to object

---

webpack.config.js

WEBUI-441: append path separator for tmp resources (3.0.x)

---

elements/diff/nuxeo-diff.js

WEBUI-261: Rely on document specific schemas instead of type schemas for diff (3.0.x)

---

elements/diff/nuxeo-diff.html

WEBUI-261: Rely on document specific schemas instead of type schemas for diff (10.10)

---

elements/nuxeo-document-bulk-actions/nuxeo-delete-documents-button.js

Backport of https://github.com/nuxeo/nuxeo-web-ui/pull/1293

WEBUI-459: set syncIndexing for delete documents action - 3.0.x

---

.github/workflows/promote.yaml
Jenkinsfile
elements/nuxeo-admin/nuxeo-repository-analytics.js
elements/nuxeo-admin/nuxeo-search-analytics.js
elements/nuxeo-admin/nuxeo-workflow-analytics.js
elements/workflow/paralleldocumentreview/nuxeo-task2169-layout.html
elements/workflow/paralleldocumentreview/nuxeo-task2556-layout.html
elements/workflow/paralleldocumentreview/nuxeo-task328d-layout.html
elements/workflow/serialdocumentreview/nuxeo-task38e-layout.html
elements/workflow/serialdocumentreview/nuxeo-task6d8-layout.html
i18n/messages-pl.json
package.json

Related to https://github.com/nuxeo/nuxeo-elements/pull/456.

WEBUI-458: backport missing stuff from master to 3.0

---

README.md

Related to https://github.com/nuxeo/nuxeo-elements/pull/457.

WEBUI-458: deprecate master branch
